/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsIndexRouteImport } from './routes/assignments.index'
import { Route as AssignmentsOutputRouteImport } from './routes/assignments.output'
import { Route as AssignmentsCreateRouteImport } from './routes/assignments.create'
import { Route as AssignmentsOutputIdRouteImport } from './routes/assignments.output.$id'

const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsIndexRoute = AssignmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssignmentsRoute,
} as any)
const AssignmentsOutputRoute = AssignmentsOutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => AssignmentsRoute,
} as any)
const AssignmentsCreateRoute = AssignmentsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AssignmentsRoute,
} as any)
const AssignmentsOutputIdRoute = AssignmentsOutputIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssignmentsOutputRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/groups': typeof GroupsRoute
  '/library': typeof LibraryRoute
  '/toolkit': typeof ToolkitRoute
  '/assignments/create': typeof AssignmentsCreateRoute
  '/assignments/output': typeof AssignmentsOutputRouteWithChildren
  '/assignments/': typeof AssignmentsIndexRoute
  '/assignments/output/$id': typeof AssignmentsOutputIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/library': typeof LibraryRoute
  '/toolkit': typeof ToolkitRoute
  '/assignments/create': typeof AssignmentsCreateRoute
  '/assignments/output': typeof AssignmentsOutputRouteWithChildren
  '/assignments': typeof AssignmentsIndexRoute
  '/assignments/output/$id': typeof AssignmentsOutputIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/groups': typeof GroupsRoute
  '/library': typeof LibraryRoute
  '/toolkit': typeof ToolkitRoute
  '/assignments/create': typeof AssignmentsCreateRoute
  '/assignments/output': typeof AssignmentsOutputRouteWithChildren
  '/assignments/': typeof AssignmentsIndexRoute
  '/assignments/output/$id': typeof AssignmentsOutputIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/groups'
    | '/library'
    | '/toolkit'
    | '/assignments/create'
    | '/assignments/output'
    | '/assignments/'
    | '/assignments/output/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/library'
    | '/toolkit'
    | '/assignments/create'
    | '/assignments/output'
    | '/assignments'
    | '/assignments/output/$id'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/groups'
    | '/library'
    | '/toolkit'
    | '/assignments/create'
    | '/assignments/output'
    | '/assignments/'
    | '/assignments/output/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRouteWithChildren
  GroupsRoute: typeof GroupsRoute
  LibraryRoute: typeof LibraryRoute
  ToolkitRoute: typeof ToolkitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/': {
      id: '/assignments/'
      path: '/'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AssignmentsIndexRouteImport
      parentRoute: typeof AssignmentsRoute
    }
    '/assignments/output': {
      id: '/assignments/output'
      path: '/output'
      fullPath: '/assignments/output'
      preLoaderRoute: typeof AssignmentsOutputRouteImport
      parentRoute: typeof AssignmentsRoute
    }
    '/assignments/create': {
      id: '/assignments/create'
      path: '/create'
      fullPath: '/assignments/create'
      preLoaderRoute: typeof AssignmentsCreateRouteImport
      parentRoute: typeof AssignmentsRoute
    }
    '/assignments/output/$id': {
      id: '/assignments/output/$id'
      path: '/$id'
      fullPath: '/assignments/output/$id'
      preLoaderRoute: typeof AssignmentsOutputIdRouteImport
      parentRoute: typeof AssignmentsOutputRoute
    }
  }
}

interface AssignmentsOutputRouteChildren {
  AssignmentsOutputIdRoute: typeof AssignmentsOutputIdRoute
}

const AssignmentsOutputRouteChildren: AssignmentsOutputRouteChildren = {
  AssignmentsOutputIdRoute: AssignmentsOutputIdRoute,
}

const AssignmentsOutputRouteWithChildren =
  AssignmentsOutputRoute._addFileChildren(AssignmentsOutputRouteChildren)

interface AssignmentsRouteChildren {
  AssignmentsCreateRoute: typeof AssignmentsCreateRoute
  AssignmentsOutputRoute: typeof AssignmentsOutputRouteWithChildren
  AssignmentsIndexRoute: typeof AssignmentsIndexRoute
}

const AssignmentsRouteChildren: AssignmentsRouteChildren = {
  AssignmentsCreateRoute: AssignmentsCreateRoute,
  AssignmentsOutputRoute: AssignmentsOutputRouteWithChildren,
  AssignmentsIndexRoute: AssignmentsIndexRoute,
}

const AssignmentsRouteWithChildren = AssignmentsRoute._addFileChildren(
  AssignmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRouteWithChildren,
  GroupsRoute: GroupsRoute,
  LibraryRoute: LibraryRoute,
  ToolkitRoute: ToolkitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
